### ISSUE TITLE
[Epic] Docs general improvement/incorporating feedback (2023)

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/docs.waku.org#102]
**Planned start date**: 01 Jun 2023
**Due date**: 31 Dec 2023

# Summary

Tracks incorporating feedback and general improvement for work already delivered and for which the milestone is closed.
This milestone is to be kept open until end of 2023.

# Acceptance Criteria

- Reached end of 2023
- All feedback has been considered
- Identified improvements have been tackled

## Tasks

- [x] #99 

# RAID (Risks, Assumptions, Issues and Dependencies)

- Docs needs to be read for feedback to be provided

**Comment by LordGhostX** [comment]
**Weekly Update**

_achieved_: rewrote the docs in UK English
_next_: announce js-waku docs

**Comment by LordGhostX** [comment]
**Weekly Update**

- _next_: refactor the layout of the docs to match the new designs

**Comment by fryorcraken** [comment]
>     * _next_: refactor the layout of the docs to match the new designs

Is this done @LordGhostX ?

**Comment by LordGhostX** [comment]
> > ```
> > * _next_: refactor the layout of the docs to match the new designs
> > ```
> 
> Is this done @LordGhostX ?

https://github.com/waku-org/docs.waku.org/pull/140 resolves this

**Comment by LordGhostX** [comment]
**Weekly Update**

- _achieved_: added light mode toggle, updated the logos preset, added TWN guide, updated docs design and structure

**Comment by LordGhostX** [comment]
**Weekly Update**

- _achieved_: add RN warning, add certbot instructions, improve nwaku-compose guide

**Comment by fryorcraken** [comment]
@LordGhostX to update issue to list next steps (diagram feedback).
