### ISSUE TITLE
REST API/ NodeJS

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/docs.waku.org#123]
Give pointer to REST API:

> https://rfc.vac.dev/spec/16/
> https://rfc.vac.dev/spec/16/#method-naming
> openapi yaml files presents in subfolders of https://github.com/waku-org/nwaku/tree/ce5fb3401da4365c0dc8ae4428f34d3a5ecac1a5/waku/waku_api/rest

And also a guide.

Also, encourage usage of nwaku in docker with REST API for NodeJS apps.

**Comment by LordGhostX** [comment]
**Weekly Update**

- _achieved_: added references for the REST API
