### ISSUE TITLE
Document how to use k-anonymity with content topic

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/docs.waku.org#146]
Discourage developers to use PII in the content topic (such as a public key) but instead create buckets (such as first 4 bytes of hash of public key).

Attached to that some recommended practice. E.g if 1000 users, then use one content topic, if 10,000, use 10, etc.

**Comment by LordGhostX** [comment]
@fryorcraken I've opened https://github.com/waku-org/docs.waku.org/pull/148 to tackle this issue.

Changed the structure of the content topic naming considerations section and included the creation of buckets you mentioned above

I need some clarity on the recommended practice. Why should developers use 1 for 1k and 10 for 10k?

Also, are there any more recommended practices

**Comment by fryorcraken** [comment]
If an app uses a single content topic, then all users' traffic will be in this topic.
So any user using req-res protocols (filter, store) will receive all the app messages.

This can be fine if the traffic is low. Do not that RLN does apply so there are limit on traffic.

However, if this too much traffic to handle on mobile or App, then developers can create a bucket.

Starting with an unique identifier, depending on the app it could be:
- id / public key of recipient
- id / public key of sender
- id of a _room_ or _group_ or other sort of app domain topic.

One can do a hash of this _id_

```
import { sha256 } from "@noble/hashes/sha256";
import { bytesToHex } from "@waku/utils/bytes";

const hash = sha256
  .create()
  .update(/* id */)
  .digest();
// a56145270ce6b3bebd1dd012b73948677dd618d496488bc608a3cb43ce3547dd
console.log(bytesToHex(hash))
```

by including the first char of the hash in the content topic: `/my-app/0/a/proto` then the user traffic gets divided in 16: 16 possible value.

Which means that statiscally, users will only download a 16th of what they were downloading a single content topic was used.
Note: this is just a statistic, as the distribution may not be even.

Depending on the expected traffic and actual number of users or _id_ then the developer can decide to include several first bytes in the content topic. or even increase it over time.

this is the _k_ value of _k-anonymity_.

k is equal to the number of _id_ for whom the first char of the hash is "a".

if an application has 10,000 users. then using a single pubsub topic will give k = 10,000.

Using the first char of the hash id will give k = 10,000/16 = 625

**Comment by LordGhostX** [comment]
**Weekly Update**

- _achieved_: restructured content topic considerations #148
- _next_: go in-depth on k-anonymity #146

**Comment by LordGhostX** [comment]
**Weekly Update**

- _achieved_: add content topic buckets consideration #153
