### ISSUE TITLE
Remove JSON-RPC API references

### ISSUE THREAD

**Issue by NagyZoltanPeter** [waku-org/docs.waku.org#183]
As with the close of [chore: Remove json-rpc](https://github.com/waku-org/nwaku/issues/2053) we shall remove all JSON-RPC API references from nwaku documentation. Where it needs we shall point to [REST-API reference page](https://waku-org.github.io/waku-rest-api)

This is part of milestone: https://github.com/waku-org/pm/milestone/14

**Comment by LordGhostX** [comment]
Hi,

The JSON-RPC references were removed a long time ago (last year). The following pages already mention the REST API:

- https://docs.waku.org/#more-integrations
- https://docs.waku.org/guides/nwaku/faq
- https://docs.waku.org/guides/js-waku/run-waku-nodejs
- https://docs.waku.org/guides/nwaku/configure-nwaku#configure-rest-api-server
- https://docs.waku.org/guides/nwaku/run-docker-compose#use-the-rest-api
- https://docs.waku.org/guides/nwaku/run-node#interact-with-the-node
- Nwaku sidebar of the guides section

**Comment by NagyZoltanPeter** [comment]
> Hi,
> 
> The JSON-RPC references were removed a long time ago (last year). The following pages already mention the REST API:
> 
> * https://docs.waku.org/#more-integrations
> * https://docs.waku.org/guides/nwaku/faq
> * https://docs.waku.org/guides/js-waku/run-waku-nodejs
> * https://docs.waku.org/guides/nwaku/configure-nwaku#configure-rest-api-server
> * https://docs.waku.org/guides/nwaku/run-docker-compose#use-the-rest-api
> * https://docs.waku.org/guides/nwaku/run-node#interact-with-the-node
> * Nwaku sidebar of the guides section

I still see config options that are removed also now from code base.
https://docs.waku.org/guides/nwaku/config-options#json-rpc-config
Hopefully it is just that.

**Comment by LordGhostX** [comment]
Resolved by https://github.com/waku-org/docs.waku.org/pull/186
