### ISSUE TITLE
More graphs

### ISSUE THREAD

**Issue by D4nte** [waku-org/docs.waku.org#7]
Here are a list of graphs that would help explain Waku's architecture:

- [x] (1) Message flow architecture diagram:
	- Shows Waku Relay and pubsub topic message routing
	- Shows Filter/Light Push/Store usage with content topic usage/filtering.
	- could include information about transports used (tcp, websocket) if does not make it too busy
	- Include adaptive node information: cloud vs laptop (native) vs mobile vs browser
- [x] (2) architecture diagram of Discovery: DNS Discovery + Discv5 + peer exchange + peer persistence
- [ ] (3) Explanation diagram of RLN (there are some existing)
- [x] (4) Explanation diagram/data flow diagram of nwaku (and possibly generalized to any Waku client) 
- [x] (5) explanation of [57/STATUS-Simple-Scaling](https://rfc.vac.dev/spec/57/) (not sure about this one)

**Comment by fryorcraken** [comment]
(1) and (4) are needed for portfolio
