### ISSUE TITLE
`master` not deployed on docs.waku.org

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/docs.waku.org#75]
Latest push on `master` was not deployed on https://docs.waku.org.

It should look like https://dev-docs.waku.org (new theme applied).

Is that supposed to be the CI pipeline? https://ci.infra.status.im/job/website/job/docs.waku.org/ No jobs seem to have run on it.

Cc @serhanwbahar

**Comment by jakubgs** [comment]
Both jobs work as expected:

* https://ci.infra.status.im/job/website/job/docs.waku.org/
* https://ci.infra.status.im/job/website/job/dev-docs.waku.org/
