### ISSUE TITLE
Postgress pre-requisite in n-waku repo

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/docs.waku.org#78]
We need to properly inform the users about an important pre-requisite related to Postgres.

On Linux, there is a need to have libpq.5.so properly installed. To achieve that, the user needs to invoke the next command:

To install the pre-requisite on Ubuntu:
```
sudo apt install libpq5
```

To install the pre-requisite on Fedora:
@vpavlin - kindly add the command when possible :)
```
TBD
```

On Mac OS, the `libpq.dylib` should be installed beforehand.

To install the pre-requisite on Mac:
@weboko , @alrevuelta - kindly bring how did you install it :)
```
TBD
```

**Comment by weboko** [comment]
@LordGhostX correctly mentioned the fix that worked for me 
https://github.com/waku-org/docs.waku.org/pull/80/files#diff-f3893b9356f4e150e3aa6fc5ead5a9959102d2dd2fcb31462507748891b78db9R50
